-- Migration number: 0002
CREATE TABLE IF NOT EXISTS board (
    id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    width INTEGER NOT NULL,
    height INTEGER NOT NULL,
    is_complete BOOLEAN NOT NULL DEFAULT(FALSE),
    created_at DATETIME NOT NULL DEFAULT(DATETIME())
);

CREATE TABLE IF NOT EXISTS pixel (
    id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    board_id INTEGER NOT NULL,
    x INTEGER NOT NULL,
    y INTEGER NOT NULL,
    color INTEGER NOT NULL,
    created_at DATETIME NOT NULL DEFAULT(DATETIME()),

    FOREIGN KEY(board_id) REFERENCES board(id)
);